services:
  postgres:
    container_name: my_ecom_postgres
    image: postgres
    ports:
      - "1010:5432"
    volumes:
      - ecom-pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  ecom-pg-data: