spring:
  application:
    name: api-gateway

# Api-Gateway Configurations:
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/v1/orders/**
#            filters:
#              - AddRequestHeader=X-Custom-Header, Harshil
#              - RedirectTo=302, https://github.com/HarshilChampaneri
          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/api/v1/products/**
#            filters:
#              - AddRequestHeader=X-Custom-Header, Harshil
#              - RedirectTo=302, https://github.com/HarshilChampaneri
          - id: no-service
            uri: lb://NO-SERVICE
            predicates:
              - Path=/api/v1/no-service/**
#            filters:
#              - AddRequestHeader=X-Custom-Header, Harshil
#              - RedirectTo=302, https://github.com/HarshilChampaneri

# Eureka Client Configurations:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30