spring:
  application:
    name: inventory-service

# PostgreSQL Database Configurations:
  datasource:
    url: jdbc:postgresql://localhost:1010/inventory_db
    username: user
    password: pass

# Jpa & Hibernate Configurations:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Server Configurations:
server:
  port: 9010
  servlet:
    context-path: /api/v1
